changed deployment script

diff --git a/.github/workflows/deploy_development.yml b/.github/workflows/deploy_development.yml
--- a/.github/workflows/deploy_development.yml
+++ b/.github/workflows/deploy_development.yml
@@ -14,15 +14,80 @@ jobs:
     runs-on: ubuntu-latest
     environment: development
     steps:
-    - uses: actions/checkout@main
-    - uses: jeanlescure/react-deploy-to-s3-action@main
-      with:
-        args: --acl public-read --follow-symlinks --delete
+    - name: Checkout repo
+      uses: actions/checkout@v3
+    - name: Setup Node JS
+      uses: actions/setup-node@v3
+        with:
+          node-version: 18
+    - name: Install dependencies
+      run: npm install
+    - name: Build app
+      run: npm build
+    - name: Send to AWS S3 bucket and invalidate cache
       env:
         NODE_ENV: development
         AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
         AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
         AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
         AWS_REGION: eu-west-1
-        SOURCE_DIR: build
         CLOUDFRONT_DISTRIBUTION_ID: ${{ secrets.AWS_CLOUDFRONT_DISTRIBUTION_ID }}
+      run: |
+        set -e
+
+        if [ -z "$AWS_S3_BUCKET" ]; then
+          echo "AWS_S3_BUCKET is not set. Quitting."
+          exit 1
+        fi
+
+        if [ -z "$AWS_ACCESS_KEY_ID" ]; then
+          echo "AWS_ACCESS_KEY_ID is not set. Quitting."
+          exit 1
+        fi
+
+        if [ -z "$AWS_SECRET_ACCESS_KEY" ]; then
+          echo "AWS_SECRET_ACCESS_KEY is not set. Quitting."
+          exit 1
+        fi
+
+        if [ -z "$AWS_REGION" ]; then
+          echo "AWS_REGION is not set. Quitting."
+          exit 1
+        fi
+
+        if [ -z "$AWS_CLOUDFRONT_DISTRIBUTION_ID" ]; then
+          echo "AWS_CLOUDFRONT_DISTRIBUTION_ID is not set. Quitting."
+          exit 1
+        fi
+
+        # Create a dedicated profile for this action to avoid conflicts
+        # with past/future actions.
+        aws configure --profile react-deploy-to-s3-action <<-EOF > /dev/null 2>&1
+        ${AWS_ACCESS_KEY_ID}
+        ${AWS_SECRET_ACCESS_KEY}
+        ${AWS_REGION}
+        text
+        EOF
+
+        aws s3 sync build s3://${AWS_S3_BUCKET}/ \
+          --profile react-deploy-to-s3-action \
+          --no-progress
+
+        aws cloudfront create-invalidation \
+          --distribution-id ${CLOUDFRONT_DISTRIBUTION_ID} \
+          --paths /\*"
+
+        aws configure --profile react-deploy-to-s3-action <<-EOF > /dev/null 2>&1
+        null
+        null
+        null
+        text
+        EOF
+
+        if [ $SUCCESS -eq 0 ]
+        then
+          echo "Deploy successful."
+        else
+          echo "Failed to perform deploy!"
+          exit 1
+        fi
